// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/proto/OrchestratorServer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_pkg_proto_OrchestratorServer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_OrchestratorServer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_OrchestratorServer_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Operand1      float32                `protobuf:"fixed32,2,opt,name=Operand1,proto3" json:"Operand1,omitempty"`
	Operand2      float32                `protobuf:"fixed32,3,opt,name=Operand2,proto3" json:"Operand2,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=Operation,proto3" json:"Operation,omitempty"`
	OperationTime int32                  `protobuf:"varint,5,opt,name=OperationTime,proto3" json:"OperationTime,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_pkg_proto_OrchestratorServer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_OrchestratorServer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pkg_proto_OrchestratorServer_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetOperand1() float32 {
	if x != nil {
		return x.Operand1
	}
	return 0
}

func (x *Task) GetOperand2() float32 {
	if x != nil {
		return x.Operand2
	}
	return 0
}

func (x *Task) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Task) GetOperationTime() int32 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_pkg_proto_OrchestratorServer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_OrchestratorServer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_OrchestratorServer_proto_rawDescGZIP(), []int{2}
}

func (x *ServerResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Result        float32                `protobuf:"fixed32,2,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_pkg_proto_OrchestratorServer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_OrchestratorServer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pkg_proto_OrchestratorServer_proto_rawDescGZIP(), []int{3}
}

func (x *Result) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Result) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_pkg_proto_OrchestratorServer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_OrchestratorServer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_OrchestratorServer_proto_rawDescGZIP(), []int{4}
}

func (x *ResultRequest) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_pkg_proto_OrchestratorServer_proto protoreflect.FileDescriptor

const file_pkg_proto_OrchestratorServer_proto_rawDesc = "" +
	"\n" +
	"\"pkg/proto/OrchestratorServer.proto\x12\x13orchestrator_server\"\x0e\n" +
	"\fEmptyMessage\"\xaa\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1a\n" +
	"\bOperand1\x18\x02 \x01(\x02R\bOperand1\x12\x1a\n" +
	"\bOperand2\x18\x03 \x01(\x02R\bOperand2\x12\x1c\n" +
	"\tOperation\x18\x04 \x01(\tR\tOperation\x12$\n" +
	"\rOperationTime\x18\x05 \x01(\x05R\rOperationTime\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\tR\x06Status\"?\n" +
	"\x0eServerResponse\x12-\n" +
	"\x04Task\x18\x01 \x01(\v2\x19.orchestrator_server.TaskR\x04Task\"0\n" +
	"\x06Result\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06Result\x18\x02 \x01(\x02R\x06Result\"D\n" +
	"\rResultRequest\x123\n" +
	"\x06Result\x18\x01 \x01(\v2\x1b.orchestrator_server.ResultR\x06Result2\xc1\x01\n" +
	"\x13OrchestratorService\x12S\n" +
	"\aGetTask\x12!.orchestrator_server.EmptyMessage\x1a#.orchestrator_server.ServerResponse\"\x00\x12U\n" +
	"\n" +
	"SendResult\x12\".orchestrator_server.ResultRequest\x1a!.orchestrator_server.EmptyMessage\"\x00B>Z<github.com/ERRORIK404/Distribution_gRPC_Calculator/pkg/protob\x06proto3"

var (
	file_pkg_proto_OrchestratorServer_proto_rawDescOnce sync.Once
	file_pkg_proto_OrchestratorServer_proto_rawDescData []byte
)

func file_pkg_proto_OrchestratorServer_proto_rawDescGZIP() []byte {
	file_pkg_proto_OrchestratorServer_proto_rawDescOnce.Do(func() {
		file_pkg_proto_OrchestratorServer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_OrchestratorServer_proto_rawDesc), len(file_pkg_proto_OrchestratorServer_proto_rawDesc)))
	})
	return file_pkg_proto_OrchestratorServer_proto_rawDescData
}

var file_pkg_proto_OrchestratorServer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_OrchestratorServer_proto_goTypes = []any{
	(*EmptyMessage)(nil),   // 0: orchestrator_server.EmptyMessage
	(*Task)(nil),           // 1: orchestrator_server.Task
	(*ServerResponse)(nil), // 2: orchestrator_server.ServerResponse
	(*Result)(nil),         // 3: orchestrator_server.Result
	(*ResultRequest)(nil),  // 4: orchestrator_server.ResultRequest
}
var file_pkg_proto_OrchestratorServer_proto_depIdxs = []int32{
	1, // 0: orchestrator_server.ServerResponse.Task:type_name -> orchestrator_server.Task
	3, // 1: orchestrator_server.ResultRequest.Result:type_name -> orchestrator_server.Result
	0, // 2: orchestrator_server.OrchestratorService.GetTask:input_type -> orchestrator_server.EmptyMessage
	4, // 3: orchestrator_server.OrchestratorService.SendResult:input_type -> orchestrator_server.ResultRequest
	2, // 4: orchestrator_server.OrchestratorService.GetTask:output_type -> orchestrator_server.ServerResponse
	0, // 5: orchestrator_server.OrchestratorService.SendResult:output_type -> orchestrator_server.EmptyMessage
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_OrchestratorServer_proto_init() }
func file_pkg_proto_OrchestratorServer_proto_init() {
	if File_pkg_proto_OrchestratorServer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_OrchestratorServer_proto_rawDesc), len(file_pkg_proto_OrchestratorServer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_OrchestratorServer_proto_goTypes,
		DependencyIndexes: file_pkg_proto_OrchestratorServer_proto_depIdxs,
		MessageInfos:      file_pkg_proto_OrchestratorServer_proto_msgTypes,
	}.Build()
	File_pkg_proto_OrchestratorServer_proto = out.File
	file_pkg_proto_OrchestratorServer_proto_goTypes = nil
	file_pkg_proto_OrchestratorServer_proto_depIdxs = nil
}
